### PR TITLE
mirage.io moves to mirageos.org

### PR DESCRIPTION
**Pull request by hannesm**
Please check and test carefully, since I don't have a clue on how such a rename should be done, and whether any other steps are necessary. Thanks a lot.

Reference: https://github.com/mirage/mirage-www/pull/845

Note: the DNS entries for ci.mirageos.org and deploy.mirageos.org are already established.

### CODE REVIEW

**Comment by hannesm** [comment]
Also, I'm not sure which branch this should be PRed to -- somehow there's a live-mirage branch that is 74 commits behind the main branch...

**Comment by mtelvers** [comment]
The PR needs to go to `master` as you have it.  There are three different deployments from this repo, so we have three `live-` branches so we can target the update to the specific instance.  Therefore, we will also push this to `live-mirage`.

We will need to update the `Caddyfile` and Docker stack to reflect these changes as well.  I'll do that now and then commit the PR.

**Comment by hannesm** [comment]
Thanks mark. There's also https://github.com/ocurrent/mirage-ci/pull/48 related to this PR.

**Comment by hannesm** [comment]
I wonder, somehow new PRs such as https://github.com/mirage/mirage-skeleton/pull/405 don't seem to trigger the mirage-ci anymore. I don't quite understand how the CI is triggered, but is there something that potentially needs to be changed?

**Comment by mtelvers** [comment]
The notifications from the a GitHub app.  The payload deliveries failed as they hit a HTTP 301 and GitHub doesn't follow redirects.  I have updated the delivery URL so this should be working as expected now.

**Comment by hannesm** [comment]
> The notifications from the a GitHub app. The payload deliveries failed as they hit a HTTP 301 and GitHub doesn't follow redirects. I have updated the delivery URL so this should be working as expected now.

Thanks for your investigation and fix. I adapted on mirage/mirage-dev mirage/mirage and mirage/mirage-skeleton these webhooks. The latter one still claims to have received a 301 (with the url now pointing to ci.mirageos.org)...

**Comment by mtelvers** [comment]
Does the 301 persist when you redeliver the payload?  If so, we should investigate further.

**Comment by hannesm** [comment]
I don't know how to redeliver the payload. There's no "test" button I can see, only an edit and delete. I can add a commit to the PR...

**Comment by mtelvers** [comment]
ok - it must be different on a webhook.  On the GitHub Application, there is a 'redeliver' button against the failed deliveries.

**Comment by hannesm** [comment]
good news, it worked now (pushing another commit, the webhook says it was successful, and CI is there) :)

**Pull request merged**
