### PR TITLE
update IP address of mirage host

### PR DESCRIPTION
**Pull request by hannesm**
it recently moved to a new host

### CODE REVIEW

**Comment by mtelvers** [comment]
I think you will also need to update `config/ssh/known_hosts` to remove the old host id and add the new one.  Otherwise, `ssh` prompts to accept the fingerprint.

**Comment by hannesm** [comment]
Thanks for your information, @mtelvers.

**Comment by mtelvers** [comment]
It looks like your new hosts is missing `rsync` to complete the deployment.

https://deploy.ocamllabs.io/job/2022-11-22/141409-mirage-deploy-2682fe

**Comment by mtelvers** [comment]
I have done: `apt install rsync`, plus `mkdir /srv/unikernels` and the deployer has completed.

**Comment by hannesm** [comment]
Thanks @mtelvers, than this and #150 are fine to be merged.

**Review by mtelvers — APPROVED** [review]

**Pull request merged**
